openapi: 3.0.0

info:
  version: 1.0.0
  title: Sync
  description: Sync backend for apps.

externalDocs:
  description: Find out more about note
  url: https://github.com/abaldeweg/sync

servers:
  - url: http://localhost:8000/api

tags:

paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

security:
  - bearerAuth: []
