openapi: 3.0.0

info:
    version: 1.0.0
    title: Sync
    description: Sync backend for apps.

externalDocs:
    description: Find out more about note
    url: https://github.com/abaldeweg/sync

servers:
    - url: http://localhost:8000/api

tags:
    - name: user
      description: User

paths:
    # User
    /me:
        get:
            tags:
                - user
            description: Shows the current User
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /password:
        put:
            tags:
                - user
            description: Updates the password
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - password
                            properties:
                                password:
                                    type: string
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /login_check:
        post:
            tags:
                - user
            description: Authenticates the user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                "200":
                    description: Returns a new token
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - token
                                    - refresh_token
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    /token/refresh:
        post:
            tags:
                - user
            description: Returns a new token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - refresh_token
                            properties:
                                refresh_token:
                                    type: string
            responses:
                "200":
                    description: Returns the token
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - token
                                    - refresh_token
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

    # items
    /item/:
        get:
            tags:
                - items
            description: Returns a list of items
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/ItemResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /item/new:
        post:
            tags:
                - items
            description: Creates a new item
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ItemRequest"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ItemResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /item/{item}:
        get:
            tags:
                - items
            parameters:
                - name: item
                  in: path
                  required: true
                  description: Name of the item
                  schema:
                      type: string
            description: Returns an item
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ItemResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
        put:
            tags:
                - items
            parameters:
                - name: item
                  in: path
                  required: true
                  description: Name of the item
                  schema:
                      type: string
            description: Updates an item
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ItemRequest"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ItemResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
        delete:
            tags:
                - items
            parameters:
                - name: item
                  in: path
                  required: true
                  description: Name of the item
                  schema:
                      type: string
            description: Deletes an item
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ItemResponse"
                "401":
                    description: Access token is missing or invalid
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        ErrorResponse:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                message:
                    type: string

        UserResponse:
            type: object
            required:
                - id
                - username
                - roles
                - branch
                - isUser
                - isAdmin
            properties:
                id:
                    type: integer
                username:
                    type: string
                roles:
                    type: array
                    items:
                        type: string
                branch:
                    type: object
                    properties:
                        id:
                            type: string
                        name:
                            type: string
                        steps:
                            type: string
                        currency:
                            type: string
                        ordering:
                            type: string
                isUser:
                    type: boolean
                isAdmin:
                    type: boolean

        ItemRequest:
            type: object
            required:
                - name
                - body
            properties:
                name:
                    type: string
                body:
                    type: string

        ItemResponse:
            type: object
            required:
                - id
                - user
                - name
                - body
            properties:
                id:
                    type: integer
                user:
                    type: object
                name:
                    type: string
                body:
                    type: string

security:
    - bearerAuth: []
